declare namespace U8 {
    interface PO_POMain {
        cappcode: string, //请购单号
        carrivalplace: string, //到货地址
        cauditdate: string, //审核日期
        caudittime: Date, //审核时间
        cbg_auditor: string, //"预算审批人"
        cbg_audittime: string, //"预算审批时间预算审批人"
        cbustype: string, //业务类型
        cchangauditDate: Date, //变更审核日期
        cchangaudittime: Date, //变更审核时间
        cchanger: string, //变更人
        cchangverifier: string, //变更审核人
        ccleanver: string, //卸载版本
        ccloser: string, //关闭人
        ccontactcode: string, //供方联系人编码
        ccurrentauditor: string, //当前审批人
        cdefine1: string, //自定义项1
        cdefine10: string, //自定义项10
        cdefine11: string, //自定义项11
        cdefine12: string, //自定义项12
        cdefine13: string, //自定义项13
        cdefine14: string, //自定义项14
        cdefine15: number, //自定义项15
        cdefine16: number, //自定义项16
        cdefine2: string, //自定义项2
        cdefine3: string, //自定义项3
        cdefine4: Date, //自定义项4
        cdefine5: number, //自定义项5
        cdefine6: Date, //自定义项6
        cdefine7: number, //自定义项7
        cdefine8: string, //自定义项8
        cdefine9: string, //自定义项9
        cdepcode: string, //部门编码
        cexch_name: string, //币种名称
        clocker: string, //锁定人
        cmaker: string, //制单人
        cmaketime: Date, //制单时间
        cmemo: string, //备注
        cmodifyDate: Date, //修改日期
        cmodifytime: Date, //修改时间
        controlresult: number, //控制结果
        cpaycode: string, //付款条件编码
        cperiod: string, //物料需求计划周期
        cpersoncode: string, //业务员编码
        cpoid: string, //采购订单号
        cptcode: string, //采购类型编码
        creviser: string, //修改人
        csccode: string, //发运方式编码
        cstate: number, //状态
        csysbarcode: string, //单据条码
        cvenaccount: string, //供方银行账号
        cvenbank: string, //供方银行名称
        cvencode: string, //供应商编码
        cvenperson: string, //供方联系人
        cvenpuomprotocol: string, //收付款协议编码
        cverifier: string, //审核人
        dcloseDate: Date, //关闭日期
        dclosetime: Date, //关闭时间
        dpodate: Date | string, //单据日期
        ibargain: number, //订金
        ibg_overflag: number, //"预算审批状态"
        icost: number, //运费
        idiscounttaxtype: number, //扣税类别 (0应税外加,1应税内含)
        iflowid: number, //"流程id"
        iprintcount: number, //打印次数
        ireturncount: number, //打回次数
        iswfcontrolled: boolean, //是否启用工作流
        itaxrate: number, //表头税率
        iverifystateex: number, //单据审核状态 （-1，终审不同意，0，未提交，1已提交，2，终审同意）
        ivtid: number, //单据模版号
        nflat: number, //汇率
        poid: number | string, //采购订单主表标识
    }

    interface PO_PODetails {
        bgsp: number, //是否质检
        btaxcost: boolean, //价格标准(0无税,1含税）
        cbcloseDate: Date, //行关闭日期
        cbcloser: string, //行关闭人
        cbclosetime: Date, //行关闭时间
        cbg_auditopinion: string, //"审批意见"
        cbg_calibercode1: string, //"口径1编码"
        cbg_calibercode2: string, //"口径2编码"
        cbg_calibercode3: string, //"口径3编码"
        cbg_calibercode4: string, //口径4编码
        cbg_calibercode5: string, //口径5编码
        cbg_calibercode6: string, //口径6编码
        cbg_caliberkey1: string, //"口径1类型编码"
        cbg_caliberkey2: string, //"口径2类型编码口径2类型编码"
        cbg_caliberkey3: string, //"口径3类型编码"
        cbg_caliberkey4: string, //口径4类型编码
        cbg_caliberkey5: string, //口径5类型编码
        cbg_caliberkey6: string, //口径6类型编码
        cbg_caliberkeyname1: string, //口径1类型名称
        cbg_caliberkeyname2: string, //口径2类型名称
        cbg_caliberkeyname3: string, //口径3类型名称
        cbg_caliberkeyname4: string, //口径4类型名称
        cbg_caliberkeyname5: string, //口径5类型名称
        cbg_caliberkeyname6: string, //口径6类型名称
        cbg_calibername1: string, //"口径1名称"
        cbg_calibername2: string, //"口径2名称"
        cbg_calibername3: string, //"口径3名称"
        cbg_calibername4: string, //口径4名称
        cbg_calibername5: string, //口径5名称
        cbg_calibername6: string, //口径6名称
        cbg_itemcode: string, //"预算项目编码"
        cbg_itemname: string, //"预算项目"
        cbmemo: string, //行备注
        cbsysbarcode: string, //行条码
        cdefine22: string, //表体自定义项22
        cdefine23: string, //表体自定义项23
        cdefine24: string, //表体自定义项24
        cdefine25: string, //表体自定义项25
        cdefine26: number, //表体自定义项26
        cdefine27: number, //表体自定义项27
        cdefine28: string, //表体自定义项28
        cdefine29: string, //表体自定义项29
        cdefine30: string, //表体自定义项30
        cdefine31: string, //表体自定义项31
        cdefine32: string, //表体自定义项32
        cdefine33: string, //表体自定义项33
        cdefine34: number, //表体自定义项34
        cdefine35: number, //表体自定义项35
        cdefine36: Date, //表体自定义项36
        cdefine37: Date, //表体自定义项37
        cfree1: string, //存货自由项1
        cfree10: string, //存货自由项10
        cfree2: string, //存货自由项2
        cfree3: string, //存货自由项3
        cfree4: string, //存货自由项4
        cfree5: string, //存货自由项5
        cfree6: string, //存货自由项6
        cfree7: string, //存货自由项7
        cfree8: string, //存货自由项8
        cfree9: string, //存货自由项9
        cinvcode: string, //存货编码
        citem_class: string, //项目大类编码
        citemcode: string, //项目编码
        citemname: string, //项目名称
        contractcode: string, //合同号
        contractrowguid: any, //合同子表表识
        contractrowno: string, //合同标的编码
        cpoid: string, //采购订单号
        csocode: string, //销售订单编号
        csoordercode: string, //销售订单号
        csource: string, //单据来源
        cunitid: string, //计量单位编码
        cupsocode: string, //来源单据号
        cxjspdids: string, //询价审批单子表id
        darriveDate: Date, //计划到货日期
        fexnum: number, //出口件数
        fexquantity: number, //出口数量
        fpoarrnum: number, //到货件数
        fpoarrquantity: number, //到货数量
        fporefusenum: number, //拒收件数
        fporefusequantity: number, //拒收数量
        fporetnum: number, //退货件数
        fporetquantity: number, //退货数量
        fpovalidnum: number, //合格件数
        fpovalidquantity: number, //合格数量
        freceivednum: number, //合格品入库数量件数
        freceivedqty: number, //合格品入库数量
        iappids: number, //采购请购单子表标识
        iarrmoney: number, //原币到货金额
        iarrnum: number, //到货辅计量数量
        iarrqty: number, //到货数量
        ibg_ctrl: number, //"是否预算控制"
        id: number, //采购订单子表标识
        idiscount: number, //原币折扣额
        iflag: number, //标志
        iinvmoney: number, //累计原币发票金额
        iinvmpcost: number, //最高进价
        iinvnum: number, //累计发票辅计量数量
        iinvqty: number, //累计发票数量
        imoney: number, //原币无税金额
        inatarrmoney: number, //本币到货金额
        inatdiscount: number, //本币折扣额
        inatinvmoney: number, //累计本币发票金额
        inatmoney: number, //本币无税金额
        inatsum: number, //本币价税合计
        inattax: number, //本币税额
        inatunitprice: number, //本币无税单价
        inum: number, //辅计量数量
        iorderdid: number, //销售订单子表id
        iorderseq: number, //销售订单类型
        iordertype: number, //销售订单类型
        ioritotal: number, //累计原币付款
        ipertaxrate: number, //税率
        ippartid: number, //母件id
        ipquantity: number, //母件数量
        iptoseq: number, //选配序号
        iquantity: number, //数量
        iquotedprice: number, //报价
        ireceivedmoney: number, //累计原币到货金额
        ireceivednum: number, //累计到货辅计量数量
        ireceivedqty: number, //累计到货数量
        irowno: number, //行号
        isosid: number, //销售订单子表标识
        isum: number, //原币价税合计
        itax: number, //原币税额
        itaxprice: number, //原币含税单价
        itotal: number, //累计本币付款
        iunitprice: number, //原币无税单价
        ivouchrowno: number, //行号
        poid: number, //采购订单主表标识
        ppcids: number, //物料需求计划子表标识
        sodid: string, //需求跟踪子表id
        sotype: number //"需求跟踪方式需求跟踪方式需求跟踪方式"
    }

    interface MaterialApp {
        ccloser: string, //关闭人
        ccode: string, //单据号
        ccurrentauditor: string, //当前审批人
        cdefine1: string, //cdefine1
        cdefine10: string, //cdefine10
        cdefine11: string, //cdefine1
        cdefine12: string, //cdefine12
        cdefine13: string, //cdefine13
        cdefine14: string, //cdefine14
        cdefine15: number, //cdefine15
        cdefine16: number, //cdefine16
        cdefine2: string, //cdefine2
        cdefine3: string, //cdefine3
        cdefine4: Date, //cdefine4
        cdefine5: number, //cdefine5
        cdefine6: Date, //cdefine6
        cdefine7: number, //cdefine7
        cdefine8: string, //cdefine8
        cdefine9: string, //cdefine9
        cdepcode: string, //部门编码
        chandler: string, //审核人
        citem_class: string, //项目大类
        citemcname: string, //项目名称
        citemcode: string, //项目编码
        cmaker: string, //制单人
        cmemo: string, //cmemo
        cmodifyperson: string, //修改人
        cname: string, //cname
        cpersoncode: string, //操作员
        crdcode: string, //出库类别
        csource: string, //来源
        csysbarcode: string, //单据条码
        cvencode: string, //供应商
        ddate: Date|string, //单据日期
        dmodifyDate: Date, //修改日期
        dnmaketime: Date, //制单时间
        dnmodifytime: Date, //修改时间
        dnverifytime: Date, //审核时间
        dveriDate: Date, //审核日期
        id: number, //id
        imquantity: number, //母件数量
        iprintcount: number, //打印次数
        ireturncount: number, //打回次数
        iswfcontrolled: number, //是否工作流控制
        iverifystate: number, //工作流审批状态
        vt_id: number //模版号
    }

    interface MaterialAppVouchs {
        autoid: number, //autoid
        cassunit: string, //辅计量单位
        cbatch: string, //批号
        cbatchproperty1: number, //属性1
        cbatchproperty10: Date, //属性10
        cbatchproperty2: number, //属性2
        cbatchproperty3: number, //属性3
        cbatchproperty4: number, //属性4
        cbatchproperty5: number, //属性5
        cbatchproperty6: string, //属性6
        cbatchproperty7: string, //属性7
        cbatchproperty8: string, //属性8
        cbatchproperty9: string, //属性9
        cbcloser: string, //行关闭人
        cbmemo: string, //表体备注
        cbsysbarcode: string, //单据行条码
        cciqbookcode: string, //手册号
        cdefine22: string, //cdefine22
        cdefine23: string, //cdefine23
        cdefine24: string, //cdefine24
        cdefine25: string, //cdefine25
        cdefine26: number, //cdefine26
        cdefine27: number, //cdefine27
        cdefine28: string, //cdefine28
        cdefine29: string, //cdefine29
        cdefine30: string, //cdefine30
        cdefine31: string, //cdefine31
        cdefine32: string, //cdefine32
        cdefine33: string, //cdefine33
        cdefine34: number, //cdefine34
        cdefine35: number, //cdefine35
        cdefine36: Date, //cdefine36
        cdefine37: Date, //cdefine37
        cexpirationdate: string, //有效期至
        cfree1: string, //cfree1
        cfree10: string, //cfree10
        cfree2: string, //cfree2
        cfree3: string, //cfree3
        cfree4: string, //cfree4
        cfree5: string, //cfree5
        cfree6: string, //cfree6
        cfree7: string, //cfree7
        cfree8: string, //cfree8
        cfree9: string, //cfree9
        cinvcode: string, //存货编码
        citem_class: string, //项目大类
        citemcname: string, //项目大类名称
        citemcode: string, //项目编码
        cmassunit: number, //保质期单位
        cmocode: string, //生产订单号
        cmolotcode: string, //生产批号
        cmworkcentercode: string, //工作中心
        cname: string, //cname
        comcode: string, //委外订单号
        copdesc: string, //工艺路线描述
        corufts: string, //原始时间戳
        cpesocode: string, //pe件需求号
        crejectcode: string, //不良品单号
        cservicecode: string, //服务单号
        csocode: string, //订单号
        cwhcode: string, //仓库编码
        dduedate: Date, //预计出库日期
        dexpirationdate: Date, //有效期计算项
        dmadedate: Date, //生产日期
        dvdate: Date, //失效日期
        foutnum: number, //出库件数
        foutquantity: number, //出库数量
        id: number, //id
        iexpiratdatecalcu: number, //有效期推算方式
        iinvexchrate: number, //换算率
        imassdate: number, //保质期
        imoseq: number, //生产订单行号
        impoids: bigint, //生产订单id
        inum: number, //件数
        invcode: string, //存货编码
        iomodid: number, //委外订单子表id
        iomomid: number, //委外订单材料id
        iopseq: string, //行号
        iordercode: string, //出库单号
        iorderdid: number, //出库id
        iorderseq: number, //出库行号
        iordertype: number, //订单类型
        ipesodid: string, //pe订单id
        ipesoseq: number, //pe订单行号
        ipesotype: number, //pe订单类型
        ipickednum: number, //已拣货件数
        ipickedquantity: number, //已拣货数量
        iquantity: number, //数量
        irowno: number, //单据体行号
        isodid: string, //需求id
        isoseq: number, //需求行号
        isotype: number //需求类型
    }

}
